In [43]:
import numpy as np

In [87]:
{
  'mean': [axis1, axis2, flattened],
  'variance': [axis1, axis2, flattened],
  'standard deviation': [axis1, axis2, flattened],
  'max': [axis1, axis2, flattened],
  'min': [axis1, axis2, flattened],
  'sum': [axis1, axis2, flattened]
}

6

In [135]:
def calculate(list):
    calculate = {}
    if(len(list) == 9):
        array = np.array(list)
        mat = array.reshape((3,3))
        
       
      
        
        
        calculate = {
            'mean': [[mat.mean(0)], [mat.mean(1)], [mat.flatten().mean()]],
            'variance': [mat.var(0), mat.var(1),  mat.flatten().var()],
            'standard deviation': [mat.std(0), mat.std(1),  mat.flatten().std()],
            'max': [mat.max(0), mat.max(1), mat.flatten().max()],
            'min': [ mat.min(0), mat.min(1), mat.flatten().min()],
            'sum': [mat.sum(0), mat.sum(1),  mat.flatten().sum()]
        }
 
        
    else:
        print("ValueError : List must contain 9 numbers")

    return calculate
    

In [136]:
calculate([1,2,3,4,5,6,7,8,9])

{'mean': [[array([4., 5., 6.])], [array([2., 5., 8.])], [5.0]],
 'variance': [array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611],
 'max': [array([7, 8, 9]), array([3, 6, 9]), 9],
 'min': [array([1, 2, 3]), array([1, 4, 7]), 1],
 'sum': [array([12, 15, 18]), array([ 6, 15, 24]), 45]}

In [59]:
a = [1,2,3,4,5,6,7,8,9]

In [125]:
a = np.array(a)
mat = a.reshape((3,3))

mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:


print(mat.mean(1))
print(mat.mean(0))

print(mat.flatten().mean())


[2. 5. 8.]
[4. 5. 6.]
5.0


In [73]:
(3+6+9)/3

6.0

In [82]:
mat.flatten().var()

6.666666666666667

In [83]:
mat.flatten().std()

2.581988897471611

In [85]:
mat.max(1)

matrix([[3],
        [6],
        [9]])